#This will deploy the application to the server using SSH. It will copy the necessary files to the server and restart the application.
name: Deploy to Server
on:
  workflow_call:

jobs:
  deploy-to-server:
    runs-on: ubuntu-latest
   

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH to Prod server and deploy the application
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_EC2_HOST }}
          username: ${{ secrets.SSH_EC2_USERNAME }}
          key: ${{ secrets.SSH_EC2_PRIVATE_KEY }}
          script: |
            echo "Installing Docker on server..."
            sudo apt update && sudo apt install docker.io  docker-compose-v2 -y
            sudo usermod -aG docker $USER && newgrp docker
            mkdir -p /home/ubuntu/devops-project
      
      - name: Copy files via SSH
        uses: appleboy/scp-action@v1
        with:
         host: ${{ secrets.SSH_EC2_HOST }}
         username: ${{ secrets.SSH_EC2_USERNAME }}
         key: ${{ secrets.SSH_EC2_PRIVATE_KEY }}

         source: docker-compose.yml
         target: ~/devops-project
        



      - name: SSH to Prod server and restart the application
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_EC2_HOST }}
          username: ${{ secrets.SSH_EC2_USERNAME }}
          key: ${{ secrets.SSH_EC2_PRIVATE_KEY }}
          script: |
           script: |
                echo "Restarting application on server..."

                echo ${{ secrets.DOCKERHUB_TOKEN }} | sudo docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

                cd ~/devops-project

                sudo docker compose down || true
                sudo docker compose up -d --build --force-recreate --pull always